### ISSUE TITLE
Investigate how to add Spring Batch readers/writes as autoconfigurable options

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-task#643]
The goal is to come up with the design and determine how to bring the popular Spring Batch readers/writes in Spring Cloud Task proper, so these readers/writes would be available as Spring Boot starters for developers.

Add Spring Boot starter for:

- [x] FlatFileItemReader 
- [x] FlatFileItemWriter

Next:
- [x] JdbcCursorItemReader — @mminella 
- [x] JdbcPagingItemReader (in progress) — @mminella 
- [x] JdbcBatchItemWriter — @cppwfs 
- [x] KafkaItemReader (in PR) — @cppwfs  
- [x] KafkaItemWriter  (in PR) — @cppwfs  
- [x] RabbitItemReader (in PR) — @cppwfs 
- [x] RabbitItemWriter (in PR) — @cppwfs 

Previous experiments: https://github.com/mminella/spring-boot-starter-singlestepjob

**Comment by sabbyanandan** [comment]
The scope of this epic is complete.
